// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc6XRp5d-UtbO18arvazS4ZAW05b3OUuk',
    appId: '1:878639215664:web:ca4bb346e84db11998e9f5',
    messagingSenderId: '878639215664',
    projectId: 'nector-cda3f',
    authDomain: 'nector-cda3f.firebaseapp.com',
    storageBucket: 'nector-cda3f.firebasestorage.app',
    measurementId: 'G-1D5LSCY019',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqPZn-s5HpiofvE9H07tnTEYfWR7QTRAQ',
    appId: '1:878639215664:android:94b6d46a727f8e4898e9f5',
    messagingSenderId: '878639215664',
    projectId: 'nector-cda3f',
    storageBucket: 'nector-cda3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9MgTp3nzz38Y9gy4QkBsBRM3ftGtfw4A',
    appId: '1:878639215664:ios:f4469def22aa1d0a98e9f5',
    messagingSenderId: '878639215664',
    projectId: 'nector-cda3f',
    storageBucket: 'nector-cda3f.firebasestorage.app',
    iosBundleId: 'com.example.nector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9MgTp3nzz38Y9gy4QkBsBRM3ftGtfw4A',
    appId: '1:878639215664:ios:f4469def22aa1d0a98e9f5',
    messagingSenderId: '878639215664',
    projectId: 'nector-cda3f',
    storageBucket: 'nector-cda3f.firebasestorage.app',
    iosBundleId: 'com.example.nector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc6XRp5d-UtbO18arvazS4ZAW05b3OUuk',
    appId: '1:878639215664:web:80d4ca58f58bbc0398e9f5',
    messagingSenderId: '878639215664',
    projectId: 'nector-cda3f',
    authDomain: 'nector-cda3f.firebaseapp.com',
    storageBucket: 'nector-cda3f.firebasestorage.app',
    measurementId: 'G-CL03KXFEVH',
  );
}
